var homeContent = `<div id="home"><h1>Lorem Ipsum.</h1><img src="images/home.jpeg" /><div class="dual-text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac purus posuere diam finibus porta. Praesent a felis sit amet metus elementum maximus. Nunc euismod lacus lobortis dui ultricies euismod. Curabitur gravida leo arcu, quis accumsan elit consequat nec. Phasellus et leo eleifend, porttitor est iaculis, dignissim nunc. Quisque sed massa sapien. Nulla facilisi. Maecenas egestas convallis sodales.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac purus posuere diam finibus porta. Praesent a felis sit amet metus elementum maximus. Nunc euismod lacus lobortis dui ultricies euismod. Curabitur gravida leo arcu, quis accumsan elit consequat nec. Phasellus et leo eleifend, porttitor est iaculis, dignissim nunc. Quisque sed massa sapien. Nulla facilisi. Maecenas egestas convallis sodales.</p></div></div>`;

var aboutContent = `<div id="about"><div class="image-left"><img src="images/about.jpeg" /> <div class="text"><h2>Lorem Ipsum</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eget urna cursus, blandit eros vel, malesuada odio. Pellentesque vehicula efficitur felis sed mattis. Quisque id finibus diam, et ultricies turpis. In porttitor varius lacus nec molestie. Duis non neque a nisl feugiat lobortis vel nec mi. Morbi varius eu diam eu euismod. Duis et suscipit orci. Aliquam ut neque blandit tellus ullamcorper sollicitudin. Duis blandit eros non efficitur interdum. Sed non porttitor lacus, a lacinia mi. Cras laoreet placerat est, ac vulputate lorem commodo non. Donec et magna dapibus, gravida nulla eu, mollis diam. Proin a orci nunc.</p></div></div><div class="headshots"><img src="images/headshot1.jpeg" /><img src="images/headshot2.jpeg" /><img src="images/headshot3.jpeg" /></div><p class="about-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus rhoncus, urna vel auctor lobortis, lectus sapien lobortis turpis, dignissim scelerisque elit odio a urna. Nunc nec mi quis risus pulvinar lacinia. Vestibulum vel sodales nunc. Ut ac elit quam. Maecenas ac neque scelerisque risus gravida semper congue id mauris. Duis ornare a lectus a pulvinar. Curabitur lacinia fringilla faucibus. Nulla volutpat elementum sapien in feugiat. Etiam at malesuada elit.
<br /> <br />
Vivamus sed pulvinar augue. Praesent sed posuere nisl. Ut dictum lorem odio, vitae mollis elit convallis vel. Morbi mollis volutpat arcu non semper. Maecenas ut nunc metus. Nunc porttitor pharetra dignissim. Morbi eget leo vel magna consequat pulvinar. Maecenas condimentum porta urna at vestibulum.</p></div>`;

var productsContent = `<div id="products"><div class="product-panel"><img src="images/product1.jpeg" /><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sed massa vitae arcu laoreet faucibus. Cras volutpat blandit eros non facilisis. Sed vehicula dolor sed felis finibus accumsan. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut sagittis molestie leo vel interdum. Morbi hendrerit justo iaculis leo vulputate, at euismod nisl condimentum. Mauris maximus, tellus eu faucibus vestibulum, turpis nulla ultricies velit, non vehicula augue arcu id magna. Nunc eleifend egestas pellentesque. Etiam vestibulum mauris ex, ut ultricies urna scelerisque vel. Ut consequat, lectus vel facilisis convallis, libero lorem imperdiet metus, in consectetur sapien nisi id lorem. Curabitur in turpis eget felis lacinia cursus nec sit amet orci. Morbi eu nisl sed enim elementum egestas. Sed tempus semper rutrum. Donec tellus ligula, commodo eget dui a, luctus laoreet leo. In fringilla auctor egestas.</p></div><div class="product-panel"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis ex non nibh tempus viverra. Nunc tristique dignissim dui, quis pulvinar felis interdum eget. In hac habitasse platea dictumst. Morbi a eros facilisis mi porta imperdiet ut sed lacus. Integer at nulla turpis. In ut magna placerat, dignissim purus quis, bibendum lorem. Maecenas non augue eu tortor efficitur mattis. Pellentesque rutrum consectetur finibus. Donec vulputate venenatis nulla quis aliquet. Cras ut congue lectus. Integer aliquam, odio hendrerit ullamcorper viverra, odio tortor rutrum lectus, vel tempus dolor ex at augue. Praesent accumsan libero sed lobortis sagittis. Etiam consequat neque ultricies arcu elementum iaculis. Duis eget neque est. In dapibus efficitur libero, ut rhoncus sem fermentum vitae.</p><img src="images/product2.jpeg" /></div><div class="product-panel"><img src="images/product3.jpeg" /> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a commodo augue. Pellentesque eleifend nibh odio, vel vestibulum risus lacinia a. Mauris lobortis tristique tortor id tristique. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse ornare gravida pellentesque. Pellentesque in tortor in tortor maximus viverra ac sit amet augue. Cras eleifend risus sed nisl euismod dignissim.</p></div></div>`;

var contactContent = `<div id="contact"><div class="contact-form"><form><input type="text" class="half" placeholder="First Name" /><input type="text" class="half" placeholder="Last Name" /><input type="text" class="half" placeholder="Email" /><textarea rows="20" type="text" class="full" placeholder="Comment"></textarea> <button>Submit</button></form></div></div>`


export function getPageContent(pageId) {
    $("#app").html(eval(pageId));
}